server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/seckill?useUnicode=true&characterEncoding=utf-8
    username: root
    password: happy
    hikari:
      # ????
      pool-name: DateHikariCP
      # ???????
      minimum-idle: 5
      # ?????????????600000?10min?
      idle-timeout: 180000
      # ?????
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ?????????0?????????1800000?30min?
      max-lifetime: 1800000
      # ?????????30000?30??
      connection-timeout: 30000
      # ?????????????
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  # ??Mapper.xml????
  mapper-location: classpath*:/mapper/*Mapper.xml
  # ??Mybatis????????????????
  type-aliases-package: com.example.practice.pojo

# MyBatis SQL??????????????Mapper.xml?????
logging:
  level:
    com.example.practice.mapper: debug